#!/bin/bash
# Simple backup script to backup files to s3
# Requires aws package to be installed

set -eu

date_now=$(date -u -R)
backup_path="/srv/blackbox/Volume_1/backups/"
s3_remote_bucket="limed-sudoers-backupbucket"

# first things first delete all the cruft
echo "Starting backup at ${date_now}"
find ${backup_path} -name '*.DS_Store' -type f -delete
aws s3 sync ${backup_path} s3://${s3_remote_bucket} --delete --quiet
echo "Ending backup at ${date_now}"
