---
- hosts: localhost
  connection: local
  var_files:
    - './vars/main.yaml'
    - './vars/secret/main.yaml'

  tasks:
    - name: Pull docker image
      docker_image:
        name: "{{ image_name }}"
        rm: true

    - name: Start docker container
      docker_container:
        name: "{{ container_name }}"
        image: "{{ image_name }}"
        state: "{{ container_state }}"
        restart: true
        restart_policy: always
        env:
          - BACKUP_PATH: "{{ backup_path }}"
          - BACKUP_BUCKET: "{{ backup_bucket }}"
          - AWS_ACCESS_KEY_ID: "{{ aws_access_key_id }}"
          - AWS_SECRET_ACCESS_KEY: "{{ aws_secret_access_key }}"
        volume:
          - /srv/blackbox/Volume_1/backups/:/backups/
